version: "3"

services:
  menu-service:
    image: "nestjs-restaurant/bff-express-service"
    restart: always
    ports:
      - "9400:3001"
    depends_on:
      - mongo_db_menu
    networks:
      - nestjs-restaurant-network
  mongo_db_menu:
    image: "mongo:4.4.15"
    restart: always
    ports:
      - "27021:27017"
    networks:
      - nestjs-restaurant-network
networks:
  nestjs-restaurant-network:
    driver: bridge
